image: python:3

stages:
    - build
    - publish

build:
    stage: build
    script:
        - python setup.py sdist bdist_wheel

publish:
    stage: publish
    script:
        - pip install twine
        - twine upload dist/*${CI_COMMIT_TAG}.tar.gz
    only:
        - tags
    tags:
        - nuc
