image: python:3

stages:
    - deploy

deploy:
    stage: deploy
    variables:
        TWINE_USERNAME: $TWINE_USERNAME
        TWINE_PASSWORD: $TWINE_PASSWORD
    script:
        - python setup.py sdist bdist_wheel
        - pip install twine -i https://pypi.tuna.tsinghua.edu.cn/simple
        - twine upload dist/*
    only:
        - tags
    tags:
        - nuc
