image: python:3

stages:
    - deploy

deploy:
    stage: deploy
    variables:
        TWINE_USERNAME: $TWINE_USERNAME
        TWINE_PASSWORD: $TWINE_PASSWORD
    script:
        - python setup.py sdist bdist_wheel
        - pip install twine
        - twine upload dist/*${CI_COMMIT_TAG}.tar.gz
    only:
        - tags
    tags:
        - nuc
