stages:
    - deploy

deploy:
    stage: deploy
    script:
        - DATE=$(date +%Y.%m.%d)
        - TAG_NUMBER=1
        - LAST_TAG=$(git describe --tags --abbrev=0)
        - if [[ "$LAST_TAG" == *$DATE* ]]; then
          TAG_NUMBER=$((${LAST_TAG##*.} + 1))
          fi
        - NEW_TAG="$DATE.$TAG_NUMBER"
        - echo "Creating tag $NEW_TAG"
        - git tag "$NEW_TAG"
        - git push origin "$NEW_TAG"

        - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
        - pip install hatch twine
        - hatch version $NEW_TAG
        - hatch build
        - TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
        - TWINE_USERNAME=${TWINE_USERNAME} TWINE_PASSWORD=${TWINE_PASSWORD} twine upload dist/*
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

    tags:
        - nuc
