image: python:3

stages:
    - deploy

deploy:
    stage: deploy
    variables:
        TWINE_USERNAME: gitlab-ci-token
        TWINE_PASSWORD: ${CI_JOB_TOKEN}
    script:
        - python setup.py sdist bdist_wheel
        - pip install twine -i https://pypi.tuna.tsinghua.edu.cn/simple
        - twine upload dist/* --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    only:
        - tags
    tags:
        - nuc
