image: python:3

stages:
    - deploy

deploy:
    stage: deploy
    script:
        - python setup.py sdist bdist_wheel
        - pip install twine -i https://pypi.tuna.tsinghua.edu.cn/simple
        - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    only:
        - tags
    tags:
        - nuc
