[project]
    authors = [{ name = "Bean", email = "bean@yuanfen.net" }]
    classifiers = [
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        'Programming Language :: Python',
    ]
    dependencies = [
        "chardet~=5.2",
        "pydantic~=2.10",
        "pytz~=2025.1",
        "pyyaml~=6.0",
        "redis~=7.0",
        "requests~=2.0",
        "watchdog~=6.0",
    ]
    description = "Yuanfen Python Library"
    license = { text = "MIT" }
    name = "yuanfen"
    readme = "README.md"
    requires-python = ">=3.9"
    version = "0.0.0"

[project.urls]
    repository = "https://github.com/YuanfenNet/yf-lib-py"

[dependency-groups]
    dev = ["ruff>=0.14.1"]
